/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/app/fusion-theme.ts
 * Command: astryx theme build src/app/fusion-theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./fusion.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const fusionTheme: DefinedTheme;
